version: '2'

services:
    api:
        build: ./
        command: src/api.py
        restart: always
        environment:
            - PGHOST=postgres
        ports:
            - 5000:5000
        depends_on:
            - postgres

    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        
        environment:
            - POSTGRES_HOST=172.18.0.3
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=sorted_data
  