version: '2'

services:
    http_server:
        build: ./
        command: src/http_server.py
        restart: always
        environment:
            PGHOST: postgres
        ports:
            - 5000:5000
        networks:
            - default
        depends_on:
            - postgres

    socket_server:
        build: ./
        command: src/socket_server.py
        restart: always
        networks:
            - default
        depends_on:
            - postgres

    module_test:
        build: ./
        command: test/test_module.py
        environment:
            PGHOST: postgres_test
        networks:
            - default
        depends_on:
            - postgres_test

    integration_test:
        build: ./
        command: test/test_integration.py
        environment:
            PGHOST: postgres_test
        networks:
            - default
        depends_on:
            - postgres_test


    postgres:
        image: postgres:latest
        ports:
            - 5432:5432

        networks:
            - default

        environment:
            - POSTGRES_HOST=172.18.0.3
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=math_data

    postgres_test:
        image: postgres:latest
        ports:
            - 5433:5433

        networks:
            - default

        environment:
            - POSTGRES_HOST=172.18.0.3
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=1234
            - POSTGRES_DB=test_db

networks:
  default:
